In [ ]:
import numpy as np

In [ ]:
inputs = np.array([[0,1,0],[1,0,1],[0,0,1],[1,1,0]])
outputs = np.array([[0],[1],[0],[1]])

In [ ]:
inputs

array([[0, 1, 0],
       [1, 0, 1],
       [0, 0, 1],
       [1, 1, 0]])

In [ ]:
outputs

array([[0],
       [1],
       [0],
       [1]])

In [ ]:
weights = np.random.random((3,1))
weights

array([[0.12897709],
       [0.00083795],
       [0.64320194]])

In [ ]:
sum = np.dot(inputs,weights) + 0.02
sum

array([[0.02083795],
       [0.79217902],
       [0.66320194],
       [0.14981504]])

In [ ]:
def activation(x):
  return 1/ (1+np.exp(-x))

In [ ]:
sum = np.dot(inputs,weights) + 0.02
ypred = activation(sum)
ypred

array([[0.5052093 ],
       [0.68829902],
       [0.65997929],
       [0.53738386]])

In [ ]:
error = outputs - ypred
error

array([[-0.5052093 ],
       [ 0.31170098],
       [-0.65997929],
       [ 0.46261614]])

In [ ]:
def gradient(x,e):
  return e * (x * (1-x))

In [ ]:
sum = np.dot(inputs,weights) + 0.02
ypred = activation(sum)
error = outputs - ypred
cha_weights = gradient(ypred,error)  ### gradient descent
weights = weights + np.dot(inputs.T,cha_weights)
error

array([[-0.49661328],
       [ 0.27536804],
       [-0.62112438],
       [ 0.38706057]])

In [ ]:
for i in range(1000):
  sum = np.dot(inputs,weights) + 0.02
  ypred = activation(sum)
  error = outputs - ypred
  cha_weights = gradient(ypred,error)  ### gradient descent
  weights = weights + np.dot(inputs.T,cha_weights)
error

array([[-0.01892395],
       [ 0.01332676],
       [-0.01892395],
       [ 0.01332676]])

In [ ]:
ypred

array([[0.02337012],
       [0.98355851],
       [0.02337012],
       [0.98355851]])

In [ ]:
inputs.T.shape

(3, 4)

In [ ]:
cha_weights.shape

(4, 1)