In [1]:
import numpy as np

In [2]:
#our basic dataset
x = np.array([[0,1,0],[1,0,1],[1,1,0],[0,0,1]])
y = np.array([[0],[1],[1],[0]])

In [3]:
x

array([[0, 1, 0],
       [1, 0, 1],
       [1, 1, 0],
       [0, 0, 1]])

In [4]:
y

array([[0],
       [1],
       [1],
       [0]])

In [5]:
1/(1+np.exp(-2.0))

0.8807970779778823

In [9]:
###Assign the weights
np.random.seed(10) #fixing the waights
weights = np.random.random((3,1))
weights

array([[0.77132064],
       [0.02075195],
       [0.63364823]])

In [10]:
### Multiply and sum (input and weights)
sum = np.dot(x,weights)
sum

array([[0.02075195],
       [1.40496888],
       [0.79207259],
       [0.63364823]])

In [11]:
def activation(x):    #sigmoid
  return 1/(1+np.exp(-x))

In [12]:
activation(22)

0.9999999997210531

In [13]:
sum = np.dot(x,weights) + 0.02
ypred = activation(sum)
ypred

array([[0.51018658],
       [0.8061162 ],
       [0.69255099],
       [0.65783211]])

In [14]:
ypred.round()

array([[1.],
       [1.],
       [1.],
       [1.]])

In [15]:
sum = np.dot(x,weights) + 0.02
ypred = activation(sum)
error = y - ypred
error

array([[-0.51018658],
       [ 0.1938838 ],
       [ 0.30744901],
       [-0.65783211]])

In [16]:
def gradient(x,a):
  return a*(x*(1-x))

In [17]:
sum = np.dot(x,weights) + 0.02
ypred = activation(sum)
error = y - ypred
change_in_weight = gradient(ypred,error)    ### gradient descent
weights = weights + np.dot(x.T,change_in_weight)
error

array([[-0.51018658],
       [ 0.1938838 ],
       [ 0.30744901],
       [-0.65783211]])

In [18]:
for i in range(500):
  sum = np.dot(x,weights) + 0.02
  ypred = activation(sum)
  error = y - ypred
  change_in_weight = gradient(ypred,error)    ### gradient descent
  weights = weights + np.dot(x.T,change_in_weight)
  #error

In [19]:
error

array([[-0.04888703],
       [ 0.0341874 ],
       [ 0.03418747],
       [-0.04888713]])

In [20]:
ypred

array([[0.04888703],
       [0.9658126 ],
       [0.96581253],
       [0.04888713]])

In [22]:
ypred.round()

array([[0.],
       [1.],
       [1.],
       [0.]])